spring:
  application:
    name: school-service
---
spring:
  profiles: public
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.199.112:3306/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: test123
    password: Test#@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://192.168.50.201:9411/zipkin/
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.50.201:8761/eureka/
  instance:
    prefer-ip-address: true
---
spring:
  profiles: private
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.230.199.112:3306/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: test123
    password: Test#@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:8060
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8084
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true