server:
  port: 8084
  address: 127.0.0.1
spring:
  application:
    name: school-service
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://devops2:12305/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: bocloud@2019
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:8060
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true