server:
  address: 127.0.0.1
  port: 8084
spring:
  application:
    name: school-service
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTER_ADDRESS:localhost:8761}/eureka/
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}