server:
  port: 8060
spring:
  application:
    name: zipkin-server
eureka:
  client:
    serviceUrl:
  #   defaultZone: http://192.168.50.201:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false
