server:
  port: 8060
spring:
  application:
    name: zipkin-server
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
eureka:
  client:
    serviceUrl:
  #   defaultZone: http://192.168.50.201:8761/eureka/
      defaultZone: http://${server.address}:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  metrics:
    web:
      server:
        auto-time-requests: false