server:
  port: 8040
spring:
  application:
    name: gateway-zuul
  zipkin:
    base-url: http://localhost:8060
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
#      defaultZone: http://192.168.50.201:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    school-route:
      path: /school/**
      service-id: school-service
      strip-prefix: false
    teacher-route:
      path: /teacher/**
      service-id: teacher-service
      strip-prefix: false
    student-route:
      path: /student/**
      service-id: student-service
      strip-prefix: false