server:
  port: 8040
spring:
  application:
    name: gateway-zuul
  zipkin:
    base-url: http://172.18.0.1:8060
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.18.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    shutdown:
      enabled: false
zuul:
  routes:
    school-route:
      path: /school/**
      service-id: school-service
      strip-prefix: false
    teacher-route:
      path: /teacher/**
      service-id: teacher-service
      strip-prefix: false
    student-route:
      path: /student/**
      service-id: student-service
      strip-prefix: false