spring:
  profiles:
    #激活开发环境
    active: dev
---
#开发环境配置
spring:
  profiles: dev
server:
  port: 8082
  address: 127.0.0.1
---
#灰度发布测试
spring:
  profiles: gray
server:
  port: 8072
  address: 127.0.0.1
---
spring:
  application:
    name: teacher-service
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:12305/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: bocloud@2019
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true
management:
  metrics:
    tags:
      application: ${spring.application.name}