spring:
  profiles:
    #激活开发环境
    active: dev
---
#开发环境配置
spring:
  profiles: dev
server:
  port: 8082
  address: 127.0.0.1
---
#灰度发布测试
spring:
  profiles: gray
server:
  port: 8072
  address: 127.0.0.1
---
spring:
  application:
    name: teacher-service
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://devops2:12305/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: bocloud@2019
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://${server.address}:8060
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.address}:8761/eureka/
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true