spring:
  profiles:
    #激活开发环境
    active: dev
---
#开发环境配置
spring:
  profiles: dev
server:
  port: 8083
  address: 127.0.0.1
---
#灰度发布测试
spring:
  profiles: gray
server:
  port: 8073
  address: 127.0.0.1
---
spring:
  application:
    name: student-service
  datasource:
    dirver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS:localhost:3306}/cloudtest?characterEncoding=utf-8&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
feign:
  hystrix:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    ip-address: ${server.address}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}