# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven And Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
      with:
        # Docker Version
        docker_version: 19.03 # optional, default is 19.03
        # Docker Channel
        docker_channel: stable # optional, default is stable
    - name: Build Image with Docker
      run: docker build -t datacenter-school:latest school && docker save datacenter-school:latest > datacenter-school-latest.tar
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: ./datacenter-school-latest.tar
